name: Tests
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
        rails:
          - '5.0'
          - '5.1'
          - '5.2'
          - '6.0'
        exclude:
          - rails: '6.0'
            ruby: '2.4'
    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.x.gemfile
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-ruby@v1.1.1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: bundle install
      - run: bundle exec rake
